#!/bin/sh
. /etc/hotplug.d/mac-utils

HOSTS_DIR="/tmp/hosts"
LOGGER_NAME="hotplug[neigh]"
LOG_FACILITY="user"


if [ -z "$IPADDR" ]; then
    echo "Invalid IP address: $IPADDR" >&2
    exit 1
fi

logmsg() {
    priority="$1"
    action="$(printf "%-010s" "$2")"
    message="$3"
    echo "${action} | ${message}" | logger -p "${LOG_FACILITY}.${priority}" -t "$LOGGER_NAME"
}

OUI_NAME=$(find_oui_name "$MACADDR")
ETHERS_NAME=$(find_ethers_name "$MACADDR")
MAC_IPV4_LEASE_NAME=$(find_dhcpv4_name_by_mac "$MACADDR")

# The format is <ipaddr> dev <dev> lladr <macaddr> <state keywords>
DEV=$(ip neigh show "$IPADDR" | awk '{print $3}')

LOG_LINE="$(printf "%-08s" "$DEV")| $MACADDR | $IPADDR"

chosen_name=""
if [ -n "$ETHERS_NAME" ] && [ -n "$MAC_IPV4_LEASE_NAME" ]; then
    if [ "$MAC_IPV4_LEASE_NAME" = "$ETHERS_NAME" ]; then
        chosen_name="$ETHERS_NAME"
        LOG_LINE="$LOG_LINE | $ETHERS_NAME"
    else
        chosen_name="$MAC_IPV4_LEASE_NAME"
        LOG_LINE="$LOG_LINE | $ETHERS_NAME / $MAC_IPV4_LEASE_NAME"
    fi
elif [ -n "$ETHERS_NAME" ]; then
    chosen_name="$ETHERS_NAME"
    LOG_LINE="$LOG_LINE | $ETHERS_NAME"
elif [ -n "$MAC_IPV4_LEASE_NAME" ]; then
    chosen_name="$MAC_IPV4_LEASE_NAME"
    LOG_LINE="$LOG_LINE | $chosen_name"
elif [ -n "$OUI_NAME" ]; then
    oui_hostname=$(create_oui_hostname "$OUI_NAME" "$MACADDR" 1)
    if [ -n "$oui_hostname" ]; then
        chosen_name="$oui_hostname"
        LOG_LINE="$LOG_LINE | ($oui_hostname)"
    else
        LOG_LINE="$LOG_LINE | (Unknown)"
    fi
fi

case "$OUI_NAME" in
    '')
        ;;
    LocalAdmin)
        LOG_LINE="$LOG_LINE | ${OUI_NAME}"
        ;;
    *)
        LOG_LINE="$LOG_LINE | ${OUI_NAME}"
        ;;
esac


if [ -z "$IPADDR" ]; then
    exit 1
fi

if [ -z "$DEV" ]; then
    exit 1
fi

net=${DEV#br-}
hosts_file="$HOSTS_DIR/neighbors.${net:-unknown}"
entry_from_other_hosts_files=$(grep -H "^$IPADDR" /tmp/hosts/* | grep -v "^$hosts_file" | head -n1)
entry_from_this_hosts_file=$(grep -H "^$IPADDR" "$hosts_file" | head -n1)
name_from_this_hosts_file=$(echo "$entry_from_this_hosts_file" | awk '{print $2}')

if [ "$ACTION" = "add" ]; then
    chosen_action="add"
    case "$IPADDR" in
        fe8*|fc*|fd*|ff*)
            # non-global (link-local, unique-local, or multicast) IPv6 address
            # logmsg "debug" "non-global" "$LOG_LINE"
            chosen_action="remove"
            ;;
        169.254.*.*)
            chosen_action="remove"
            ;;
        *.*.*.*)
            # IPv4 address
            if [ -n "$MAC_IPV4_LEASE_NAME" ]; then
                # DHCPv4 lease already has the name
                # logmsg "debug" "has-lease" "$LOG_LINE"
                chosen_action="remove"  # in case there's a stale entry from before the lease had a name
            elif  [ -n "$name_from_this_hosts_file" ]; then
                # logmsg "debug" "my-hosts4" "$LOG_LINE"
                # logmsg "debug" "my-hosts4" "$entry_from_this_hosts_file"
                if [ "$name_from_this_hosts_file" = "$chosen_name" ]; then
                    # if the name hasn't changed, leave the entry alone
                    exit 0
                else
                    logmsg "debug" "renamed4" "$LOG_LINE"
                fi
            elif  [ -n "$entry_from_other_hosts_files" ]; then
                # logmsg "debug" "any-hosts4" "$LOG_LINE"
                # logmsg "debug" "any-hosts4" "$entry_from_other_hosts_files"
                chosen_action="remove"
            else
                logmsg "info" "add-ipv4" "$LOG_LINE"
            fi
            ;;
        *:*)
            # IPv6 address
            if [ -n "$name_from_this_hosts_file" ]; then
                # logmsg "debug" "my-hosts6" "$LOG_LINE"
                # logmsg "debug" "my-hosts6" "$entry_from_this_hosts_file"
                if [ "$name_from_this_hosts_file" = "$chosen_name" ]; then
                    # if the name hasn't changed, leave the entry alone
                    exit 0
                else
                    logmsg "debug" "renamed6" "$LOG_LINE"
                fi
            elif [ -n "$entry_from_other_hosts_files" ]; then
                # logmsg "debug" "any-hosts6" "$LOG_LINE"
                # logmsg "debug" "any-hosts6" "$entry_from_other_hosts_files"
                chosen_action="remove"
            else
                logmsg "info" "add-ipv6" "$LOG_LINE"
            fi
            ;;
        '')
            # no address
            logmsg "error" "$ACTION" "$LOG_LINE (no IP address)"
            ;;
        *)
            # invalid address
            logmsg "debug" "invalid" "$LOG_LINE"
            exit 1
            ;;
    esac
else
    chosen_action="$ACTION"
    logmsg "info" "$ACTION" "$LOG_LINE"
fi

if [ "$chosen_action" = "add" ]; then
    if [ -n "$chosen_name"]; then
        if [ -n "$name_from_this_hosts_file" ]; then
            sed -i "/^$IPADDR/d" $hosts_file 2>/dev/null
        fi
        printf "%-40s %s\n" "$IPADDR" "$chosen_name" >> $hosts_file
    fi
elif [ "$chosen_action" = "remove" ]; then
    # Remove entry from this $HOSTS_FILE (but no other files) if IPADDR exists
    sed -i "/^$IPADDR/d" $hosts_file 2>/dev/null
fi



